{% set kubeconfig = "--kubeconfig=/var/lib/kubelet/kubeconfig" -%}
{% if grains.api_servers is defined -%}
  {% set api_servers = "--master=https://" + grains.api_servers -%}
{% elif grains['roles'][0] == 'kubernetes-master' -%}
  {% set master_ipv4 = salt['grains.get']('fqdn_ip4')[0] -%}
  {% set api_servers = "--master=https://" + master_ipv4 -%}
{% else -%}
  {% set ips = salt['mine.get']('roles:kubernetes-master', 'network.ip_addrs', 'grain').values() -%}
  {% set api_servers = "--master=https://" + ips[0][0] -%}
{% endif -%}
{% set api_servers_with_port = api_servers + ":6443" -%}

{% if grains['roles'][0] == 'kubernetes-master' -%}
  {% if grains.cloud in ['aws', 'gce', 'vagrant', 'digitalocean', 'linode', 'vultr'] -%}
    # Unless given a specific directive, disable kubelet on the master.
    {% if grains.kubelet_api_servers is defined -%}
      {% set api_servers_with_port = "--master=https://" + grains.kubelet_api_servers  + ":6443" -%}
    {% else -%}
      {% set api_servers_with_port = "" -%}
    {% endif -%}
  {% endif -%}
{% endif -%}

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: appscode-dnssyncer-0.2
  namespace: kube-system
  labels:
    k8s-app: appscode-dnssyncer
    version: '0.2'
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: appscode-dnssyncer
        version: '0.2'
        kubernetes.io/cluster-service: "true"
    spec:
      hostNetwork: true
      containers:
      - name: dnssyncer
        image: appscode/dnssyncer:0.2
        resources:
          requests:
            cpu: 100m
        command:
        - /bin/sh
        - -c
        - dnssyncer-linux-amd64 {{api_servers_with_port}} {{kubeconfig}} --hosts-file=/hosts --v=2  1>>/var/log/appscode-dnssyncer.log 2>&1
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ssl-certs-host
          readOnly: true
        - mountPath: /var/log
          name: varlog
          readOnly: false
        - mountPath: /var/lib/kubelet/kubeconfig
          name: kubeconfig
          readOnly: false
        - mountPath: /hosts
          name: hosts
      volumes:
      - hostPath:
          path: /usr/share/ca-certificates
        name: ssl-certs-host
      - hostPath:
          path: /var/lib/kubelet/kubeconfig
        name: kubeconfig
      - hostPath:
          path: /var/log
        name: varlog
      - name: hosts
        hostPath:
          path: /etc/hosts
