apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Grafana"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    k8s-app: grafana
