apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana-logging-v1
  namespace: kube-system
  labels:
    k8s-app: kibana-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kibana-logging
    version: v1
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kibana-logging
        image: appscode/kibana:4.4.2
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: sv
          protocol: TCP
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://elasticsearch-logging:9200"
      - name: kibana-proxy
        image: appscode/kibana-proxy:0.1
        args:
        - --kibana-url=http://127.0.0.1:5601
        - --v=3
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5051
          name: ui
          protocol: TCP
        volumeMounts:
        - name: appscode-cluster-metadata
          mountPath: /var/run/config/appscode
      volumes:
      - name: appscode-cluster-metadata
        configMap:
          name: cluster-metadata
