apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: searchlight-icinga
  namespace: kube-system
  labels:
    k8s-app: searchlight-icinga
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: searchlight-icinga
  template:
    metadata:
      labels:
        k8s-app: searchlight-icinga
    spec:
      containers:
      - image: appscode/icinga:1.5.9-ac
        name: icinga
        ports:
        - containerPort: 5665
          name: api
          protocol: TCP
        - containerPort: 60006
          name: tcp
          protocol: TCP
        volumeMounts:
          - name: data-volume
            mountPath: /var/pv
          - name: script-volume
            mountPath: /var/db-script
          - name: appscode-api-token
            mountPath: /var/run/secrets/appscode
          - name: appscode-cluster-metadata
            mountPath: /var/run/config/appscode
          - name: searchlight-icinga
            mountPath: /srv/icinga2/secrets
      - image: appscode/postgres:9.5-v3-db
        name: ido
        args:
          - basic
          - './setup-db.sh'
        ports:
          - containerPort: 5432
            name: ido
            protocol: TCP
        volumeMounts:
          - name: data-volume
            mountPath: /var/pv
          - name: script-volume
            mountPath: /var/db-script
      volumes:
        - name: data-volume
          emptyDir: {}
        - name: script-volume
          emptyDir: {}
        - name: appscode-api-token
          secret:
            secretName: appscode-api-token
        - name: appscode-cluster-metadata
          configMap:
            name: cluster-metadata
        - name: searchlight-icinga
          secret:
            secretName: searchlight-icinga
