apiVersion: v1
kind: ReplicationController
metadata:
  name: appscode-ossec-server
  namespace: kube-system
  labels:
    k8s-app: appscode-ossec-server
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: appscode-ossec-server
    version: v1
  template:
    metadata:
      labels:
        k8s-app: appscode-ossec-server
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: ossec-server
        image: appscode/ossec-wazuh-server:v1.0.4
        resources:
          limits:
            cpu: 100m
        ports:
        - name: ossec
          containerPort: 1514
          protocol: UDP
        - name: https
          containerPort: 55000
          protocol: TCP
        volumeMounts:
        - name: ossec-api-secrets
          mountPath: /var/ossec/api/ssl
          readOnly: true
        - name: ossec-server-data
          mountPath: /var/ossec/data
      volumes:
      - name: ossec-api-secrets
        secret:
          secretName: appscode-ossec
      - name: ossec-server-data
        emptyDir: {}
