apiVersion: v1
kind: Pod
metadata:
  name: kube-addon-manager
  namespace: kube-system
  labels:
    component: kube-addon-manager
spec:
  hostNetwork: true
  containers:
  - name: kube-addon-manager
    # When updating version also bump it in cluster/images/hyperkube/static-pods/addon-manager.json
    image: appscode/kube-addon-manager:v6.1-1.5.3
    command:
    - /bin/bash
    - -c
    - /opt/kube-addons.sh 1>>/var/log/kube-addon-manager.log 2>&1
    resources:
      requests:
        cpu: 5m
        memory: 50Mi
    volumeMounts:
    - mountPath: /etc/kubernetes/
      name: addons
      readOnly: true
    - mountPath: /var/log
      name: varlog
      readOnly: false
    - mountPath: /var/cache/kubernetes-install/
      name: kube-env
      readOnly: true
    - mountPath: /srv/
      name: srv
    - mountPath: /var/run/secrets/appscode/
      name: api-token
  volumes:
  - hostPath:
      path: /etc/kubernetes/
    name: addons
  - hostPath:
      path: /var/log
    name: varlog
  - hostPath:
      path: /var/cache/kubernetes-install/
    name: kube-env
  - hostPath:
      path: /srv/
    name: srv
  - hostPath:
      path: /var/run/secrets/appscode/
    name: api-token