apiVersion: v1
kind: Pod
metadata:
  name: kube-addon-manager
  namespace: kube-system
  labels:
    component: kube-addon-manager
    version: v4
spec:
  hostNetwork: true
  containers:
  - name: kube-addon-manager
    # When updating version also bump it in cluster/images/hyperkube/static-pods/addon-manager.json
    image: appscode/kube-addon-manager:v5.1-1.4.6
    resources:
      requests:
        cpu: 5m
        memory: 50Mi
    volumeMounts:
    - mountPath: /etc/kubernetes/
      name: addons
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/
    name: addons
