apiVersion: v1
kind: Pod
metadata:
  name: kube-addon-manager
  namespace: kube-system
  labels:
    component: kube-addon-manager
    version: v4
spec:
  hostNetwork: true
  containers:
  - name: kube-addon-manager
    image: appscode/kube-addon-manager:v5
    resources:
      requests:
        cpu: 5m
        memory: 50Mi
    volumeMounts:
    - mountPath: /etc/kubernetes/
      name: addons
      readOnly: true
    - mountPath: /var/cache/kubernetes-install/
      name: kube-env
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/
    name: addons
  - hostPath:
      path: /var/cache/kubernetes-install/
    name: kube-env
